/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ADIMINISTRADOR;

import Objetos.Adm;
import Objetos.Cliente;
import Objetos.ObjectDao;
import java.awt.Toolkit;
import java.io.File;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author valme
 */
public class TelaListarAdm extends javax.swing.JDialog {
    List<Adm> listaAdm;
    java.awt.Frame parent;
    /**
     * Creates new form TelaListarAdm
     */
    public TelaListarAdm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.parent = parent;
        ObjectDao sv = new ObjectDao();
        listaAdm = (List<Adm>)(Object)sv.show("adm");
        carregarAdm();
        setIcon();
    }
    
    
    public void carregarAdm(){
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Nome");
        modelo.addColumn("CPF");
        modelo.addColumn("Email");
        
        for (Adm ad : listaAdm){
            modelo.addRow(new Object[]{ad.getNome(),
                                       ad.getCpf(),
                                       ad.getEmail()});
        }
        jTableAdm.setModel(modelo);      
    }
    
    private void abrirAlterarAdm(){
        if(jTableAdm.getSelectedRow()>=0){
            DefaultTableModel modelo = (DefaultTableModel)jTableAdm.getModel();
            int index = jTableAdm.getSelectedRow();
            TelaAlteraAdm a = new TelaAlteraAdm(parent, true,index);
            a.setVisible(true);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAdm = new javax.swing.JTable();
        jTextFieldAdm = new javax.swing.JTextField();
        jButtonAdm = new javax.swing.JButton();
        JButtonEditar = new javax.swing.JButton();
        JButtonEditar1 = new javax.swing.JButton();
        JButtonEditar2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("VK Sistemas");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Lista de Administradores");

        jTableAdm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "CPF", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableAdm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAdmMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableAdm);

        jButtonAdm.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonAdm.setText("Pesquisar");
        jButtonAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdmActionPerformed(evt);
            }
        });

        JButtonEditar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        JButtonEditar.setText("Excluir");
        JButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonEditarActionPerformed(evt);
            }
        });

        JButtonEditar1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        JButtonEditar1.setText("Cadastrar");
        JButtonEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonEditar1ActionPerformed(evt);
            }
        });

        JButtonEditar2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        JButtonEditar2.setText("Editar");
        JButtonEditar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonEditar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonAdm, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108)
                        .addComponent(JButtonEditar2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JButtonEditar1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JButtonEditar1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JButtonEditar2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdmActionPerformed
        // TODO add your handling code here:
        String nome = jTextFieldAdm.getText();
       
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Nome");
        modelo.addColumn("CPF");
        modelo.addColumn("Email");
        
        for (Adm ad : listaAdm){
            if(ad.getNome().contains(nome)){
                modelo.addRow(new Object[]{ad.getNome(),
                                       ad.getCpf(),
                                       ad.getEmail()});
            }
        }
        jTableAdm.setModel(modelo); 
    }//GEN-LAST:event_jButtonAdmActionPerformed

    private void JButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonEditarActionPerformed
         if(0==JOptionPane.showConfirmDialog
            (this,"Tem certeza que deseja\n"
                + "excluir "+jTableAdm.getValueAt(jTableAdm.getSelectedRow(), 0),
                  "Excluir Administrador",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE)
            ){
            ObjectDao sv = new ObjectDao();
            List<Adm> listaAdm = (List<Adm>)(Object)sv.show("adm");
            new File("src\\Dados\\adm.dat").delete();
            int i = 0;
            for (Adm adm : listaAdm) {
                if(i==jTableAdm.getSelectedRow()){
                    i++;
                    continue;
                }
                sv.save("adm", adm);
                i++;
            }
        }
        carregarAdm();
    }//GEN-LAST:event_JButtonEditarActionPerformed

    private void jTableAdmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAdmMouseClicked
        if(evt.getClickCount()==2){
            DefaultTableModel modelo = (DefaultTableModel)jTableAdm.getModel();
            int selectedRowIndex = jTableAdm.getSelectedRow();
            
        }

    }//GEN-LAST:event_jTableAdmMouseClicked

    private void JButtonEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonEditar1ActionPerformed
        TelaCadastroAdm t = new TelaCadastroAdm(null, true);
        t.setVisible(true);
        carregarAdm();
    }//GEN-LAST:event_JButtonEditar1ActionPerformed

    private void JButtonEditar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonEditar2ActionPerformed
        abrirAlterarAdm();    
        carregarAdm();
    }//GEN-LAST:event_JButtonEditar2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaListarAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaListarAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaListarAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaListarAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaListarAdm dialog = new TelaListarAdm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonEditar;
    private javax.swing.JButton JButtonEditar1;
    private javax.swing.JButton JButtonEditar2;
    private javax.swing.JButton jButtonAdm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAdm;
    private javax.swing.JTextField jTextFieldAdm;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
       setIconImage(Toolkit.getDefaultToolkit().getImage("src\\Imagens\\code.png"));
    }
}
