/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TelaInicial;

import CLIENTE.TelaPrincipalCliente;
import Objetos.Adm;
import Objetos.Cliente;
import Objetos.ObjectDao;
import java.awt.Toolkit;
import java.io.File;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class login extends javax.swing.JFrame {
    List<Cliente> listaCliente;
    List<Adm> listaAdm;
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        ObjectDao sv = new ObjectDao();
        listaAdm = (List<Adm>)(Object)sv.show("adm");
        carregarClientes();
         setIcon();
    }
    public void carregarClientes(){
        if(new File("src\\Dados\\cliente.dat").exists()){
            ObjectDao sv = new ObjectDao();
            listaCliente = (List<Cliente>)(Object)sv.show("cliente");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        btnEntrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        jbCadastrar = new javax.swing.JButton();
        txtLogin = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VK Sistemas");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Livraria Almeida Diniz");
        jLayeredPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 73));

        btnEntrar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        jLayeredPane1.add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 220, 120, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("CPF:");
        jLayeredPane1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Senha:");
        jLayeredPane1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        txtSenha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLayeredPane1.add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 280, 28));

        jbCadastrar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbCadastrar.setText("Cadastrar");
        jbCadastrar.setOpaque(false);
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jbCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        try {
            txtLogin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtLogin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLayeredPane1.add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 280, -1));

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 270));

        setSize(new java.awt.Dimension(378, 323));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        TelaCadastroCliente c = new TelaCadastroCliente(this,true);
        c.setVisible(true);
        carregarClientes();
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed

        String login = txtLogin.getText();
        String password = String.valueOf(txtSenha.getPassword());
 
        boolean achou = false;
     
        for(Adm a : listaAdm){
            if((a.getCpf().equalsIgnoreCase(login)) && (a.getSenha().equals(password))){
                 achou = true;
                 //entra tela do ADM
                 this.dispose();
            }
        }
        
        for (Cliente cli : listaCliente){
            System.out.println(cli);
            if((cli.getCpf().equalsIgnoreCase(login)) && (cli.getSenha().equals(password))){                
                achou = true;
                TelaPrincipalCliente t =new TelaPrincipalCliente(cli);
                t.setVisible(true);
                this.dispose();
            }  
        }
       
        if(!achou){
            JOptionPane.showMessageDialog(null, "Login ou Senha Inválidos");
        }
        
    
    }//GEN-LAST:event_btnEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JFormattedTextField txtLogin;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage("src\\Imagens\\code.png"));
    }
}

